version: '3.7'
services:
    learning:
        image: wordem:latest
        volumes:
            - type: volume
              source: output
              target: /app/output
            - type: bind
              source: /etc/localtime
              target: /etc/localtime
volumes:
    output:
